### ISSUE TITLE
Error installing packages 

### ISSUE THREAD

**Issue by sweebee** [michbeck100/pimatic-hap#2]
I tried `sudo apt-get install libnss-mdns libavahi-compat-libdnssd-dev` but I get this error:

```
ns libavahi-compat-libdnssd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libavahi-compat-libdnssd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by sweebee** [comment]
and when installing pimatic-hap:

```
> curve25519@1.1.0 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/obj.target/curve.node
  SOLINK_MODULE(target) Release/obj.target/curve.node: Finished
  COPY Release/curve.node
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/curve25519/build'

> mdns@2.2.10 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
dns_sd_bindings.target.mk:131: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 

> ed25519@0.0.3 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild


node.js:811
    var cwd = process.cwd();
                      ^

Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:811:23)
    at startup (node.js:58:13)
    at node.js:902:3
npm ERR! mdns@2.2.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.10 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-hap"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE

> bignum@0.11.0 install /home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

chdir(): No such file or directory
```

**Comment by michbeck100** [comment]
My guess would be that the compile error is because the package and with the header dns_sd.h isn't available. Could you try this: http://www.blackmoreops.com/2014/12/13/fixing-error-package-packagename-not-available-referred-another-package-may-mean-package-missing-obsoleted-available-another-source-e-pa/

**Comment by michbeck100** [comment]
Did you solve your problem? If yes, just close this issue. Thanks

**Comment by sweebee** [comment]
Still no luck.

tried:

```
root@pimatic-thuis:~# sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get install libavahi-compat-libdnssd-dev
```

and 

```
apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get install libavahi-compat-libdnssd-dev
```

All the same error.

Error

```
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 libraspberrypi0 : Depends: raspberrypi-bootloader (= 1.20150923-1) but 1.20150421-1 is installed
E: Unmet dependencies. Try using -f.
```

also tried with -f and got same error.

**Comment by michbeck100** [comment]
Seems you're the only one facing this problem. I must admit, i have no idea what the problem could be. Which raspberry pi distro are you using? Are you using a raspberry pi at all?

**Comment by sweebee** [comment]
i'm using a RPI 2 with raspbian. But i will reinstall everything since my other pimatic installation (at work) works fine.

**Comment by sweebee** [comment]
Re-installed raspbian and its working fine now.
