### ISSUE TITLE
change temperature on COMETDECT-FRITZ!Box Thermostat through pimatic-hap

### ISSUE THREAD

**Issue by amiraoul** [michbeck100/pimatic-hap#53]
99% of the time the temp change through pimatic-hap / homekit doesn't always work

When changing the temp these are the 2 diffrent error which happen:
- temp automatically changes every second up or down til restart of pimatic
- home app tries to change the temp during a couple of min without success (exclamation marks error in home app thermostat widget) --> produces error in pimatic log

error seems related to pimatic-hap since changing temp directly in pimatic works flawless

error [pimatic]: A uncaught exception occured: Error: changeModeTo must be implemented by a subclass
    at FritzThermostatDevice.HeatingThermostat.changeModeTo (/home/amiraoul/pimatic-app/node_modules/pimatic/lib/devices.coffee:602:17)
    at [object Object].<anonymous> (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/accessories/thermostat.coffee:68:20)
    at emitMany (events.js:108:13)
    at [object Object].emit (events.js:182:7)
    at [object Object].Characteristic.setValue (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Bridge.<anonymous> (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Accessory.js:727:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Accessory.js:672:8)
    at emitMany (events.js:108:13)
    at HAPServer.emit (events.js:182:7)
    at HAPServer._handleCharacteristics (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/HAPServer.js:967:10)
    at HAPServer.<anonymous> (/home/amiraoul/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/HAPServer.js:204:39)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by michbeck100** [comment]
Thanks for your bug report. I'll have a look into this.

**Comment by michbeck100** [comment]
Which version of pimatic-hap are you using? The current version 0.9.0 should actually fix the first problem.

**Comment by amiraoul** [comment]
I'm using 0.9.0 since it has been released.
I will do some further testing and keep you posted on the first issue.
The second issue is definitely present since i have a scene defined in the apple home app to disable couple of lights and lower the temp on a thermostat.

**Comment by michbeck100** [comment]
I've created a PR for pimatic-fritz to solve the second problem which produces the error.

**Comment by michbeck100** [comment]
My PR was merged and pimatic-fritz was released in version 0.5.3. Please update and open this issue again if you still have problems.
